"""
Sionna Channel Map Lookup — runtime SINR interpolation.

Loads a pre-computed .npz channel map (generated by channel_precompute.py)
and provides O(1) bilinear interpolation for any (lat, lng) position.

When no map is available for a region, falls back to the 3GPP TR 38.901
2-slope path-loss model implemented in building_obstruction_analyzer._L_total().

Integration with _L_total():
  sinr_db = lookup.query_sinr(lat, lng, bs_id)
  # Replace the internal SINR computation in _L_total with this value:
  throughput_bps = mcs_table.sinr_to_throughput(sinr_db)
  latency_ms = payload_bits / throughput_bps * 1000

Reference:
  [1] Hoydis, J. et al., "Sionna: An Open-Source Library for Next-Generation
      Physical Layer Research", arXiv:2203.11189, 2022.
"""
from __future__ import annotations

import math
from pathlib import Path
from typing import Optional

import numpy as np

_MAP_DIR = Path(__file__).parent.parent.parent.parent.parent / "data" / "sionna_maps"
_NO_DATA = float("nan")

# Minimum SINR returned (even in deep shadow): −20 dB → MCS 0 fallback
_SINR_MIN_DB = -20.0
_SINR_MAX_DB = 30.0     # practical upper limit for 5G NR FR1


class ChannelLookup:
    """
    SINR map lookup for one region (one .npz file).

    Parameters
    ----------
    npz_path : Path | str
        Path to the .npz file produced by SionnaPrecomputer.
    bs_ids : list[str]
        BS IDs in the same order as the simulation (index 0, 1, …).
    """

    def __init__(self, npz_path: "Path | str", bs_ids: list[str]) -> None:
        data = np.load(str(npz_path))
        self._lat_grid = data["lat_grid"].astype(np.float64)   # [H]
        self._lng_grid = data["lng_grid"].astype(np.float64)   # [W]
        self._sinr_db  = data["sinr_db"].astype(np.float32)    # [N_bs, H, W]
        self._bs_idx   = {bid: i for i, bid in enumerate(bs_ids)}

        self._lat_min = float(self._lat_grid[0])
        self._lat_max = float(self._lat_grid[-1])
        self._lng_min = float(self._lng_grid[0])
        self._lng_max = float(self._lng_grid[-1])
        self._H = len(self._lat_grid)
        self._W = len(self._lng_grid)

    def query_sinr(self, lat: float, lng: float, bs_id: str) -> float:
        """
        Return SINR_dB at (lat, lng) for the given BS.

        Uses bilinear interpolation between the four nearest grid cells.
        Returns NaN if (lat, lng) is outside the map extent.
        Returns −20.0 dB if bs_id is not in the map.
        """
        b = self._bs_idx.get(bs_id)
        if b is None:
            return _SINR_MIN_DB

        if not (self._lat_min <= lat <= self._lat_max
                and self._lng_min <= lng <= self._lng_max):
            return _NO_DATA

        sinr = self._bilinear(lat, lng, b)
        return float(np.clip(sinr, _SINR_MIN_DB, _SINR_MAX_DB))

    def query_sinr_safe(self, lat: float, lng: float, bs_id: str,
                        fallback: float = -10.0) -> float:
        """Same as query_sinr but replaces NaN with `fallback`."""
        v = self.query_sinr(lat, lng, bs_id)
        return fallback if math.isnan(v) else v

    def _bilinear(self, lat: float, lng: float, bs_idx: int) -> float:
        """Bilinear interpolation in the 2-D grid."""
        # Find surrounding grid indices
        h_f = (lat - self._lat_min) / (self._lat_max - self._lat_min) * (self._H - 1)
        w_f = (lng - self._lng_min) / (self._lng_max - self._lng_min) * (self._W - 1)

        h0 = int(h_f);          h1 = min(h0 + 1, self._H - 1)
        w0 = int(w_f);          w1 = min(w0 + 1, self._W - 1)
        th = h_f - h0;          tw = w_f - w0

        s = self._sinr_db[bs_idx]
        return (
            s[h0, w0] * (1 - th) * (1 - tw)
            + s[h0, w1] * (1 - th) * tw
            + s[h1, w0] * th       * (1 - tw)
            + s[h1, w1] * th       * tw
        )

    # ── Statistics ────────────────────────────────────────────────────────────
    def coverage_stats(self, bs_id: str, threshold_db: float = -6.0) -> dict:
        """
        Fraction of grid cells above `threshold_db` for the given BS.
        threshold_db = −6 dB ≈ QPSK MCS 1 (minimum decodable SINR).
        """
        b = self._bs_idx.get(bs_id)
        if b is None:
            return {}
        sinr_map = self._sinr_db[b]
        total = sinr_map.size
        covered = int(np.sum(sinr_map >= threshold_db))
        return {
            "bs_id": bs_id,
            "threshold_db": threshold_db,
            "coverage_pct": round(covered / total * 100, 2),
            "mean_sinr_db": round(float(np.mean(sinr_map)), 2),
            "p5_sinr_db":   round(float(np.percentile(sinr_map, 5)), 2),
            "p95_sinr_db":  round(float(np.percentile(sinr_map, 95)), 2),
        }


class RegionChannelLookupCache:
    """
    LRU-style cache of ChannelLookup objects keyed by (osm_id, bs_ids_key).

    Avoids reloading large .npz files for every episode.
    Capacity is bounded to `max_cached` regions (default 8 → ~2 GB on A100).
    """

    def __init__(self, map_dir: Optional[Path] = None, max_cached: int = 8) -> None:
        self._map_dir = map_dir or _MAP_DIR
        self._max = max_cached
        self._cache: dict[tuple, ChannelLookup] = {}
        self._order: list[tuple] = []

    def get(self, osm_id: int, bs_ids: list[str]) -> Optional[ChannelLookup]:
        key = (osm_id, tuple(bs_ids))
        if key in self._cache:
            self._order.remove(key)
            self._order.append(key)
            return self._cache[key]

        path = self._map_dir / f"{osm_id}.npz"
        if not path.exists():
            return None

        try:
            lookup = ChannelLookup(path, bs_ids)
        except Exception as e:
            print(f"[ChannelLookup] Failed to load {path}: {e}")
            return None

        if len(self._cache) >= self._max:
            evict = self._order.pop(0)
            del self._cache[evict]

        self._cache[key] = lookup
        self._order.append(key)
        return lookup


def load_channel_lookup(
    osm_id: int,
    bs_ids: list[str],
    map_dir: Optional[Path] = None,
) -> Optional[ChannelLookup]:
    """
    Convenience function to load a single ChannelLookup.

    Returns None if no pre-computed map exists for this region.
    """
    path = (map_dir or _MAP_DIR) / f"{osm_id}.npz"
    if not path.exists():
        return None
    try:
        return ChannelLookup(path, bs_ids)
    except Exception:
        return None
